services:
  - type: web
    name: plataforma-gestao
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
